highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
  math_engine: mathjax

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      blogtitle: "Byways"
      author: "Younghoon Jung"

plugins:
  - jekyll-archives

jekyll-archives:
  enabled: [tags]
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    category: category-archive
    tag: tag-archive
  permalinks:
    year: '/archives/:year/'
    month: '/archives/:year/:month/'
    day: '/archives/:year/:month/:day/'
    tag: '/archives/tag/:name/'
    category: '/archives/category/:name/'