highlighter: none
markdown: kramdown
kramdown:
  math_engine: katex
  syntax_highlighter_opts:
    disable: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      blogtitle: "DOCs"
      author: "Younghoon Jung"

jekyll-archives:
  enabled: [tags]
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    category: category-archive
    tag: tag-archive
  permalinks:
    year: "/archives/:year/"
    month: "/archives/:year/:month/"
    day: "/archives/:year/:month/:day/"
    tag: "/archives/tag/:name/"
    category: "/archives/category/:name/"
