name: Younghoon, Jung
title: Quest for Information
description: -- write description --

# Authors
authors:
  younghoon:
    name: Younghoon, Jung
    display_name: Younghoon, Jung
    email: to.younghoon.jung@gmail.com
    web: https://younghoonjung.com

highlighter: none
markdown: kramdown
kramdown:
  math_engine: katex
  syntax_highlighter_opts:
    disable: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      blogtitle: "Q"
      author: "Younghoon Jung"

plugins:
  - jekyll-paginate
  - jekyll-archives

sass:
  sass_dir: _sass
  style: compressed

# Pagination
paginate: 6
paginate_path: /page:num/

# Archives
jekyll-archives:
  enabled: [tags]
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    category: category-archive
    tag: tag-archive
  permalinks:
    year: "/archives/:year/"
    month: "/archives/:year/:month/"
    day: "/archives/:year/:month/:day/"
    tag: "/archives/tag/:name/"
    category: "/archives/category/:name/"
