highlighter: none
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      blogtitle: "Byways"
      author: "Younghoon Jung"



jekyll-archives:
  enabled: [tags]
  layouts:
    year: year-archive
    month: month-archive
    day: day-archive
    category: category-archive
    tag: tag-archive
  permalinks:
    year: '/assets/:year/'
    month: '/assets/:year/:month/'
    day: '/assets/:year/:month/:day/'
    tag: '/assets/tag/:name/'
    category: '/assets/category/:name/'